# Generated by Django 2.1.1 on 2018-09-22 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_contacts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
