# Generated by Django 2.1.1 on 2018-09-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
